# Default values for example-chart.

# Replica count
replicaCount: 1

# Pod image
image:
  repository: "nginx"
  pullPolicy: IfNotPresent
  tag: "latest"

# Pod image pull secrets
imagePullSecrets: []

# Init containers
# initContainers:
#   - name: volume-permissions
#     image: busybox
#     command: ["sh", "-c", "chown -R 1000:1000 /usr/share/nginx/html"]
#     volumeMounts:
#       - name: html
#         mountPath: /usr/share/nginx/html

# Environment variables
envVars: []

# ConfigMap and Secret for environment variables
configMap: {}
secret:
  enabled: false
  data: {}
  stringData: {}

# Service Account
serviceAccount: {}
  # create: true
  # automount: true
  # annotations: {}
  # name: ""

# Pod Annotations and Labels
podAnnotations: {}
podLabels: {}

# Pod and Container Security Context
podSecurityContext:
  fsGroup: 33

# Service settings
service:
  type: ClusterIP
  port: 80

# Ingress settings
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Resource limits and requests
resources: {}

# Liveness and readiness probes
livenessProbe: {}
  # httpGet:
  #   path: /
  #   port: http
  # initialDelaySeconds: 5
  # periodSeconds: 10
  # timeoutSeconds: 5
  # successThreshold: 1
  # failureThreshold: 3

readinessProbe: {}
  # httpGet:
  #   path: /
  #   port: http
  # initialDelaySeconds: 5
  # periodSeconds: 10
  # timeoutSeconds: 5
  # successThreshold: 1
  # failureThreshold: 3

# Enable persistence using Persistent Volume Claims
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi
  mountPath: /usr/share/nginx/html  # Default path for NGINX content
  volumeName: html
  storageClass: ""  # Uses default storage class if not specified

# Node selector, tolerations, and affinity
nodeSelector: {}
tolerations: []
affinity: {}