{{- define "helmlet.configmap" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helmlet.fullname" . }}-config
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}