{{- define "helmlet.secret" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helmlet.fullname" . }}-secret
  labels:
    {{- include "helmlet.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secret.data }}
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
{{- if .Values.secret.stringData }}
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
{{- end -}}