{{- define "helmlet.service" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmlet.fullname" . }}
  labels:
    {{- include "helmlet.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmlet.selectorLabels" . | nindent 4 }}
{{- end }}